name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost  # Ou "mariadb-service" si déployé dans Kubernetes
      DB_PORT: 3306
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        working-directory: ./src/api
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        working-directory: ./src/api
        run: docker build -t ghcr.io/sarahzahiac/todo-app:${{ github.sha }} .

      - name: Login GHCR
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u sarahzahiac --password-stdin

      - name: Push Image
        run: docker push ghcr.io/sarahzahiac/todo-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        env:
          DB_HOST: localhost  # Ou mariadb-service
          DB_PORT: 3306
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f storageApp.yaml
          kubectl apply -f storageDB.yaml
